version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "80:80"
